spring:
    application:
        name: dropctl
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    flyway:
        enabled: true
        location: classpath:db/migration
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate

server:
    shutdown: graceful

management:
    endpoints:
        web:
            exposure:
                include: health, info
    endpoint:
        health:
            probes:
                enabled: true